env:  
  node: true
extends: airbnb-base
rules: 
  no-console: 0
  import/extensions: 0
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
# https://github.com/jest-community/eslint-plugin-jest
  - jest